monsters2
=========

Composing
---------

✓ Multi-shape objects
✓ Stroke and fill colors in objects

☐ Apply affine transforms from the inspector
☐ Apply h/v flip from the inspector

Library
-------

✓ Create thumbnail for library object
● Display thumbnail in the library

Canvas
------

✓ Save canvas to file
✓ Remove object from canvas

Saving
------

☐ Save file to gallery
☐ View files in gallery
☐ Export file to JPG, BMP, etc.